version: '3'

services:
  file-parser:
    build:
      context: .
      dockerfile: LabinventTestTask.FileParserService/Dockerfile
    restart: always
    ports:
      - "8080:8080"
      - "8081:8081"
    volumes:
      - FILEPATH:/app/data/XMLStorage
      # - .\TestData:/app/data/XMLStorage
    environment:
      - BUILD_CONFIGURATION=Release

  data-processor:
   build:
     context: .
     dockerfile: LabinventTestTask.DataProcessorService/Dockerfile
   ports:
      - "8082:8080"
      - "8083:8081"
   restart: always
   environment:
     - BUILD_CONFIGURATION=Release
     - DATABASE_URL=Data Source=/app/data/mydatabase.db 

  rabbitmq:
    build:
     context: .
     dockerfile: Docker\Dockerfile.RabbitMQ
    hostname: rabbitmq
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - rabbitmq-data:/var/lib/rabbitmq
      - ./init.sh:/usr/local/bin/init.sh

volumes:
  rabbitmq-data: