ARG DATABASE_NAME=database.db

FROM alpine:latest

RUN apk --no-cache add sqlite

RUN mkdir /data

COPY ["LabinventTestTask.DataProcessorService/$DATABASE_NAME","/data/"]

WORKDIR /data

CMD ["sqlite3", "$DATABASE_NAME"]